import React from 'react'
import { useNavigate } from 'react-router-dom'
import { Sparkles } from 'lucide-react'
import { EmptyState } from './EmptyState'

interface NotProcessedStateProps {
  datasetId: string
  what: string
}

/** Shown when an endpoint returns 404 because the dataset has not been processed yet. */
export const NotProcessedState: React.FC<NotProcessedStateProps> = ({ datasetId, what }) => {
  const navigate = useNavigate()
  return (
    <EmptyState
      icon={<Sparkles className="w-6 h-6" />}
      title="Dataset not processed yet"
      description={`${what} are generated by the multi-agent pipeline. Run the cleaning pipeline on this dataset first.`}
      actionLabel="Open Cleaning Pipeline"
      onAction={() => navigate(`/cleaning/${datasetId}`)}
    />
  )
}
